# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.4.dev161+g17ccfe3.d20221229'
__version_tuple__ = version_tuple = (0, 4, 'dev161', 'g17ccfe3.d20221229')
